--liquibase formatted sql

--changeset rhuan.resende:v2-create-table-custom-revision
CREATE TABLE IF NOT EXISTS public.customrevisionentity
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT NOT NULL,
    username VARCHAR(150)
    );

CREATE SEQUENCE IF NOT EXISTS customrevisionentity_seq
    INCREMENT BY 1
    MINVALUE 1
    START WITH 1
    NO CYCLE
    CACHE 1;

ALTER SEQUENCE customrevisionentity_seq INCREMENT BY 50;

ALTER TABLE public.customrevisionentity
    OWNER TO postgres;
