--liquibase formatted sql

--changeset rhuan.resende:v2-create-table-book
CREATE TABLE IF NOT EXISTS public.book (
                      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                      create_at TIMESTAMP,
                      name TEXT NOT NULL,
                      status SMALLINT CHECK (status >= 0 AND status <= 1)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.book
    OWNER to postgres;
