--liquibase formatted sql

--changeset rhuan.resende:v5-create-table-person
CREATE TABLE IF NOT EXISTS public.person (
                        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                        full_name VARCHAR(200) NOT NULL,
                        birth_date TIMESTAMP,
                        document VARCHAR(30) NOT NULL UNIQUE,
                        email VARCHAR(150) NOT NULL,
                        phone VARCHAR(30),
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP,
    CONSTRAINT person_pkey PRIMARY KEY (id)
)    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.person
    OWNER to postgres;