--liquibase formatted sql

--changeset rhuan.resende:v6-create-table-person-audit
CREATE TABLE IF NOT EXISTS public.person_AUD (
                            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                            rev INT NOT NULL,
                            revtype SMALLINT,
                            full_name VARCHAR(200),
                            birth_date TIMESTAMP,
                            document VARCHAR(30),
                            email VARCHAR(150),
                            phone VARCHAR(30),
                            created_at TIMESTAMP,
                            updated_at TIMESTAMP,
                            CONSTRAINT fk_person_aud_revision
                                FOREIGN KEY (rev)
                                    REFERENCES customrevisionentity(id)
)    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.person_AUD
    OWNER to postgres;