--liquibase formatted sql

--changeset rhuan.resende:v4-create-table-users
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    account_non_expired boolean,
    account_non_locked boolean,
    credentials_non_expired boolean,
    enabled boolean,
    person_id bigint NOT NULL,
    password character varying(255),
    user_name character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name),
    CONSTRAINT fk_usuario_person FOREIGN KEY (person_id) REFERENCES person(id)
    )
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER TO postgres;